services:
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?err}
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
    networks:
      - database
  
  api:
    build:
      context: api/
    restart: always
    environment:
      FRONTEND_URL: ${FRONTEND_URL:?err}
      CRON_KEY: ${CRON_KEY:?err}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      RUST_BACKTRACE: full
    networks:
      - database
    ports:
      - "3001:3000"
  
  frontend:
    build:
      context: frontend/
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:?err}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: $NEXT_PUBLIC_GOOGLE_CLIENT_ID
      NEXT_PUBLIC_GOOGLE_API_KEY: $NEXT_PUBLIC_GOOGLE_API_KEY
    ports:
      - "3000:3000"

volumes:
  db_data:

networks:
  database:
